const ACTION_TYPES = {
  TOGGLE_PRODUCT_LOADING: 'TOGGLE_PRODUCT_LOADING',
  RECEIVE_PRODUCTS: 'RECEIVE_PRODUCTS',
  RESET_PRODUCTS: 'RESET_PRODUCTS',
  REFRESH_PRODUCTS: 'REFRESH_PRODUCTS',
  DELETE_PRODUCTS: 'DELETE_PRODUCTS',

  TOGGLE_ORDER_LOADING: 'TOGGLE_ORDER_LOADING',
  RECEIVE_ORDERS: 'RECEIVE_ORDERS',
  RESET_ORDERS: 'RESET_ORDERS',
  REFRESH_ORDERS: 'REFRESH_ORDERS',
  DELETE_ORDERS: 'DELETE_ORDERS',
};

export default ACTION_TYPES;
