const ACTION_TYPES = {
  TOGGLE_PRODUCT_LOADING: 'TOGGLE_POSTS_LOADING',
  RECEIVE_PRODUCTS: 'RECEIVE_PRODUCTS',
  RESET_PRODUCTS: 'RESET_PRODUCTS',
  REFRESH_PRODUCTS: 'REFRESH_PRODUCTS',
  DELETE_PRODUCTS: 'DELETE_PRODUCTS',
};

export default ACTION_TYPES;
